### ISSUE TITLE
Expiration du token et redirection vers la page d'authentification

### ISSUE THREAD

**Issue by vinceengo** [gti525/h17-mobile-scan#10]
Quand va-t-on vérifier si le token expire?
1) À chaque requête
2) Certain fréquence

**Comment by vinceengo** [comment]
Pour application billets.

**Comment by Chunnnnn** [comment]
en fait tu vas toujours envoyer les requetes HTTP avec le token et quand il est expiré, le backend est supposé d'avertir l'app mobile (quel que soit la manière que tu veux)
